// 這是您的課程資料庫
const courses = [
    {id: "0981", name: "微積分甲〈二〉", teacher: "潘青岳", type: "compulsory", credit: 3, time: "二3,4 四6,7"},
    {id: "0982", name: "Ｃ＋＋程式設計", teacher: "焦信達", type: "compulsory", credit: 3, time: "三6,7,8 四5"},
    {id: "0983", name: "線性代數", teacher: "江岱倫", type: "compulsory", credit: 3, time: "二6,7,8"},
    {id: "0984", name: "邏輯設計", teacher: "資工教師", type: "compulsory", credit: 3, time: "五2,3,4"},
    {id: "0985", name: "邏輯設計實驗", teacher: "黃士耘", type: "compulsory", credit: 1, time: "一6,7,8"},
    {id: "0986", name: "微積分甲〈二〉", teacher: "林晢晧", type: "compulsory", credit: 3, time: "二3,4 三6,7"},
    {id: "0987", name: "Ｃ＋＋程式設計", teacher: "賴俊鳴", type: "compulsory", credit: 3, time: "二6,7,8 四6"},
    {id: "0988", name: "線性代數", teacher: "江岱倫", type: "compulsory", credit: 3, time: "一6,7,8"},
    {id: "0989", name: "邏輯設計", teacher: "劉榮春", type: "compulsory", credit: 3, time: "五2,3,4"},
    {id: "0990", name: "邏輯設計實驗", teacher: "劉榮春", type: "compulsory", credit: 1, time: "四7,8,9"},
    {id: "0991", name: "微積分甲〈二〉", teacher: "林盈郎", type: "compulsory", credit: 3, time: "二3,4 三6,7"},
    {id: "0992", name: "Ｃ＋＋程式設計", teacher: "廖元勳", type: "compulsory", credit: 3, time: "一6,7,8 三5"},
    {id: "0993", name: "線性代數", teacher: "江岱倫", type: "compulsory", credit: 3, time: "五2,3,4"},
    {id: "0994", name: "邏輯設計", teacher: "資工教師", type: "compulsory", credit: 3, time: "四6,7,8"},
    {id: "0995", name: "邏輯設計實驗", teacher: "資工教師", type: "compulsory", credit: 1, time: "五5,6,7"},
    {id: "0996", name: "Calculus A (II)", teacher: "陳宏益", type: "compulsory", credit: 3, time: "三1,2 五1,2"},
    {id: "0997", name: "C++ Programming", teacher: "賴俊鳴", type: "compulsory", credit: 3, time: "二2,3,4 四9"},
    {id: "0998", name: "Intro to ML", teacher: "呂芳懌", type: "compulsory", credit: 3, time: "一6,7,8"},
    {id: "0999", name: "程式設計檢定", teacher: "陳隆彬", type: "compulsory", credit: 1, time: "五5"},
    {id: "1000", name: "資料結構", teacher: "胡育誠", type: "compulsory", credit: 3, time: "二2,3,4"},
    {id: "1001", name: "計算機網路", teacher: "黃士耘", type: "compulsory", credit: 3, time: "三6,7,8"},
    {id: "1002", name: "系統程式", teacher: "劉榮春", type: "compulsory", credit: 3, time: "三2,3,4"},
    {id: "1003", name: "數據分析資料工程", teacher: "謝宗澔", type: "required", credit: 3, time: "五6,7,8"},
    {id: "1004", name: "計算機網路", teacher: "黃士耘", type: "compulsory", credit: 3, time: "一2,3,4"},
    {id: "1005", name: "演算法", teacher: "黃育仁", type: "compulsory", credit: 3, time: "三6,7,8"},
    {id: "1006", name: "系統程式", teacher: "陳隆彬", type: "compulsory", credit: 3, time: "四2,3,4"},
    {id: "1007", name: "數據分析資料工程", teacher: "石志雄", type: "required", credit: 3, time: "四6,7,8"},
    {id: "1008", name: "系統程式", teacher: "陳隆彬", type: "compulsory", credit: 3, time: "一6,7,8"},
    {id: "1009", name: "計算機組織", teacher: "楊朝棟", type: "compulsory", credit: 3, time: "二2,3,4"},
    {id: "1010", name: "數據分析資料工程", teacher: "廖元勳", type: "required", credit: 3, time: "三2,3,4"},
    {id: "1011", name: "專題研究", teacher: "焦信達等", type: "required", credit: 2, time: "三5,6"},
    {id: "1012", name: "專題研究", teacher: "劉榮春等", type: "required", credit: 2, time: "三5,6"},
    {id: "1013", name: "編譯器", teacher: "楊朝棟", type: "required", credit: 3, time: "一6,7,8"},
    {id: "1014", name: "Probability", teacher: "李守彧", type: "compulsory", credit: 3, time: "三2,3,4"},
    {id: "1015", name: "Linear Algebra", teacher: "李守彧", type: "compulsory", credit: 3, time: "一6,7,8"},
    {id: "1016", name: "Sys. Programming", teacher: "劉榮春", type: "compulsory", credit: 3, time: "四2,3,4"},
    {id: "1017", name: "CPE", teacher: "陳隆彬", type: "compulsory", credit: 1, time: "五6"},
    {id: "1018", name: "作業系統", teacher: "李守彧/呂芳懌", type: "compulsory", credit: 3, time: "二6,7,8"},
    {id: "1019", name: "作業系統", teacher: "呂芳懌/李守彧", type: "compulsory", credit: 3, time: "五6,7,8"},
    {id: "1020", name: "資料庫", teacher: "廖元勳", type: "compulsory", credit: 3, time: "一2,3,4"},
    {id: "1021", name: "機率學", teacher: "謝宗澔", type: "elective", credit: 3, time: "一2,3,4"},
    {id: "1022", name: "Python程式設計", teacher: "陳倫奇", type: "elective", credit: 3, time: "二2,3,4"},
    {id: "1023", name: "Linux系統管理", teacher: "林子翔", type: "elective", credit: 3, time: "五6,7,8"},
    {id: "1024", name: "軟體工程(一)", teacher: "李守彧", type: "elective", credit: 3, time: "四6,7,8"},
    {id: "1025", name: "資料壓縮", teacher: "胡育誠", type: "elective", credit: 3, time: "三2,3,4"},
    {id: "1026", name: "深度學習應用", teacher: "陳仕偉", type: "elective", credit: 3, time: "四2,3,4"},
    {id: "1027", name: "雲端計算", teacher: "焦信達", type: "elective", credit: 3, time: "五6,7,8"},
    {id: "1028", name: "機器學習導論", teacher: "陳仕偉", type: "elective", credit: 3, time: "五2,3,4"},
    {id: "1029", name: "微算機系統", teacher: "資工教師", type: "elective", credit: 3, time: "三2,3,4"},
    {id: "1030", name: "微算機系統實驗", teacher: "資工教師", type: "elective", credit: 1, time: "四2,3,4"},
    {id: "1031", name: "AIOT應用實務", teacher: "焦信達", type: "elective", credit: 3, time: "二2,3,4"},
    {id: "1032", name: "影像視訊處理", teacher: "黃育仁", type: "elective", credit: 3, time: "二6,7,8"},
    {id: "1033", name: "AI製造創新", teacher: "石志雄", type: "elective", credit: 3, time: "一2,3,4"},
    {id: "1034", name: "資訊安全概論", teacher: "林祝興", type: "elective", credit: 3, time: "二6,7,8"},
    {id: "1035", name: "無人機設計實作", teacher: "焦信達", type: "elective", credit: 3, time: "五2,3,4"},
    {id: "1036", name: "專題實作", teacher: "資工教師", type: "compulsory", credit: 2, time: "三5,6"},
    {id: "1037", name: "業界實習", teacher: "許瑞愷", type: "elective", credit: 3, time: "另訂"},
    {id: "1038", name: "企業軟體應用", teacher: "許瑞愷", type: "elective", credit: 3, time: "另訂"},
    {id: "1039", name: "職場倫理與溝通", teacher: "許瑞愷", type: "elective", credit: 3, time: "另訂"},
    {id: "3360", name: "Google Cloud 雲端運算基礎課程", teacher: "張廣欽", type: "elective", credit: 3, time: "二10, 二11, 二12"},
    {id: "3361", name: "Google Cloud 雲端運算基礎課程", teacher: "王信予", type: "elective", credit: 3, time: "三10, 三11, 三12"},
    {id: "3015", name: "人文：人文價值思辨", teacher: "廖敏君", type: "compulsory", credit: 2, time: "三7,8"},
    {id: "3018", name: "人文：人文價值思辨", teacher: "郭任峯", type: "compulsory", credit: 2, time: "三7,8"},
    {id: "3101", name: "自然：科學新知", teacher: "朱裕文", type: "compulsory", credit: 2, time: "三8,9"},
    {id: "3107", name: "自然：公共科學", teacher: "王崇名", type: "compulsory", credit: 2, time: "三8,9"}
];
